name: cantata

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/cantata/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/cantata
      repository: ${{ matrix.repository }}
