name: ccache-ext

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/ccache-ext/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/ccache-ext
      repository: ${{ matrix.repository }}
      action: build
