name: gns3-server

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/gns3-server/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/gns3-server
      repository: ${{ matrix.repository }}
