name: go2tv

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/go2tv/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/job_pkgbuild.yml
    with:
      pkgdir: aur/go2tv
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
