name: lact

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/lact/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/lact
      repository: ${{ matrix.repository }}
