name: lib32-lapack

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/lib32-lapack/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/job_pkgbuild.yml
    with:
      pkgdir: aur/lib32-lapack
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      multilib: true
      release_tag: loathk-public
