name: paru

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/paru/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/paru
      repository: ${{ matrix.repository }}
