name: python311

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/python311/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/job_pkgbuild.yml
    with:
      pkgdir: local/python311
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      makepkg_args: --skippgpcheck
      release_tag: loathk-public
