name: python311

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/python311/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public, personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: local/python311
      repository: ${{ matrix.repository }}
