name: shaderc-non-semantic-debug

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/shaderc-non-semantic-debug/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public, personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/shaderc-non-semantic-debug
      repository: ${{ matrix.repository }}
