name: tlpui

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/tlpui/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/job_pkgbuild.yml
    with:
      pkgdir: aur/tlpui
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
