
name: vicious

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - extra/vicious/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: extra/vicious
      repository: ${{ matrix.repository }}
