name: wine-ge-custom-opt

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/wine-ge-custom-opt/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public, personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/wine-ge-custom-opt
      repository: ${{ matrix.repository }}
      multilib: true
