name: wine-ge-custom

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/wine-ge-custom/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD
            multilib: true
          - repository: personal
            pkgbuild: PKGBUILD
            multilib: true
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: local/wine-ge-custom
      repository: ${{ matrix.repository }}
      pkgbuild: ${{ matrix.pkgbuild }}
      multilib: ${{ matrix.multilib }}
