name: wine

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - multilib/wine/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD
            multilib: true
          - repository: personal
            pkgbuild: PKGBUILD.wow64
            multilib: false
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: multilib/wine
      repository: ${{ matrix.repository }}
      pkgbuild: ${{ matrix.pkgbuild }}
      multilib: ${{ matrix.multilib }}
