name: xfce4-volumed-pulse

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/xfce4-volumed-pulse/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/job_pkgbuild.yml
    with:
      pkgdir: aur/xfce4-volumed-pulse
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
