
name: xiccd

on:
  workflow_dispatch:
      inputs:
        action:
          description: "Operation mode"
          required: true
          type: choice
          default: 'build'
          options:
          - 'build'
          - 'remove'
          - 'skip'
  push:
    branches:
     - master
    paths:
     - aur/xiccd/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/xiccd
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action }}
